version: "3"

services:
  angular:
    build: 
      context: ./build
    networks:
      - frontend
      - auth
      - app
    image: ruchitgandhi/mean-docker:todoapp_angular
    ports:
      - "4200:4200"
    volumes:
      - ./app:/usr/src/app/

  auth:
    networks:
      - auth
    image: ruchitgandhi/mean-docker:todoapp_express
    ports:
      - "3000:3000"
    
  app:
    networks:
      - app
    image: ruchitgandhi/mean-docker:todoapp_express

  bdd_auth:
    networks:
      - auth
    image: mongo
    ports:
      - "27017:27017"

  bdd_app:
    networks:
      - app
    image: mongo
    ports:
      - "27018:27018"

networks:
  frontend:
  auth:
  app:
